### ISSUE TITLE
Split configuration file into multiple

### ISSUE THREAD

**Issue by bonsaipuppy** [daylioti/docker-commander#12]
Right now the config.yml for DC can easily grow to 1000+ lines and there's no way to split it up.

I know yaml itself does not support imports/includes, so the handler would have to be outside of that. And it would create issues dependency wise if b.yml relies on a.yml, so load order is important.

**Comment by daylioti** [comment]
I think that it would be better to have template engine in dc configuration https://pkg.go.dev/text/template
I'll implement this in 2-nd version of dc.
Closing this issue for now.
