### ISSUE TITLE
Variable substitution - different or custom syntax

### ISSUE THREAD

**Issue by bonsaipuppy** [daylioti/docker-commander#7]
in the config file, you can reuse previously added variables (in placeholders or inputs) with adding @variable-name to any string.

in some cases this leads to substitution issues, i guess depending on which name is being searched for, first. e.g. i have two variables, "domain=one" and "domain-owner=two". which one is used first might depend on the order they were added (following the tree structure). 
but in any case, if i have a string trying to use "domain-name", i would have something like "bla @domain-owner". now with the current syntax it's not possible to decide if i actually want to display domain-owner or domain, leading to "bla one-owner" or "bla two".

being able to define a custom variable substitution syntax would be great, or prefix and postfix, so users of DC can decide themselves, for example to have "bla [domain-name]" in the end, so the substitution will be less ambiguous.

**Comment by daylioti** [comment]
Hi @s3lf Please check in 1.1.10 version
